apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: "crd-reader-role"
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefintions"]
      verbs: ["get", "list", "watch"]
