apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-deployer-rbac-binding
  namespace: demo
  #  annotations:
  #  configmanagement.gke.io/cluster-selector: app-cluster-selector
subjects:
- kind: User
  name: demo-deployer@environs-demo.iam.gserviceaccount.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
